<? $this->view('head') ?>
<title>忘记密码</title>
<link rel="stylesheet" href="<?= $this->www('css/module/index.css') ?>" type="text/css" media="screen"/>
<script type="text/javascript" src="<?= $this->www('script/module/master.index.js') ?>"></script>

<? $this->view('body') ?>
<? $this->view('default/header') ?>
        <div class="content-wrapper">
            <div class="form_block form_block-simple">
                <fieldset>
                    <legend>忘记密码</legend>
                    <form action="/master/index/do-password-recovery" method="post" id="form-password-recovery">
                        <p><label for="form-password-recovery-username">邮箱</label><input type="text" name="username" id="form-password-recovery-username" class="text required email" /></p>
                        <p><label for="form-password-recovery-captcha">验证码</label><img class="captcha" src="/com/captcha/image?a=/master/index/do-password-recovery&o=<?= time() ?>" alt="点击刷新" /><input type="text" name="captcha" id="form-password-recovery-captcha" class="text tulin required" /><a class="reload-captcha" href="javascript:;">换一张</a></p>
                        <p><input type="submit" value="取回密码" class="button green" /></p>
                    </form>
                </fieldset>
            </div>
        </div>
<? $this->view('default/footer') ?>
<script type="text/javascript">$(Z.Module.master.index.passwordRecovery.init)</script>
<? $this->view('foot') ?>
