<? $this->view('head') ?>
<title>登录房态通</title>
<link rel="stylesheet" href="<?= $this->www('css/module/index.css') ?>" type="text/css" media="screen"/>
<script type="text/javascript" src="<?= $this->www('script/module/master.index.js') ?>"></script>

<? $this->view('body') ?>
<? $this->view('default/header') ?>
        <div class="content-wrapper clearfix">
            <div class="signin-main column-right">
                <div class="form_block signin-form_block">
                    <fieldset>
                        <legend>登录房态通</legend>
                        <form action="/master/index/do-signin" method="post" id="form-signin">
                            <p><label for="form-signin-username">邮箱</label><input tabindex="1" type="text" name="username" id="form-signin-username" class="text required email" /></p>
                            <p><label for="form-signin-password">密码</label><input tabindex="2" type="password" name="password" id="form-signin-password" class="text {required:true, minlength:6}" /></p>
                            <p class="submit"><input type="submit" value="登录" class="button orange" /><a href="/master/index/password-recovery">忘记密码？</a></p>
                        </form>
                    </fieldset>
                    <p class="bottom">
                        还没有旅店帐号？ <a id="signin-signup_link" href="/master/index/signup">点击注册</a>
                    </p>
                </div>
            </div>
            <div class="signin-sub column-left">
                <div id="signin-inset"></div>
            </div>
        </div>
<? $this->view('default/footer') ?>
<script type="text/javascript">$(Z.Module.master.index.signin.init)</script>
<? $this->view('foot') ?>
