<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<!-- <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" /> -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="旅店管理，订单管理，房态管理" />
<meta name="description" content="房态通是一个....." />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="no-cache" />
<meta http-equiv="expires" content="0" />
<!-- <meta name="google-site-verification" content="" /> -->

<link rel="stylesheet" href="<?= $this->www('css/plugin.css') ?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?= $this->www('css/global.css') ?>" type="text/css" media="screen" />
<script type="text/javascript" src="<?= $this->www('script/plugin.js') ?>"></script>
<script type="text/javascript" src="<?= $this->www('script/global.js') ?>"></script>
