<? $this->view('head') ?>
<title>账单日志</title>
<link rel="stylesheet" href="<?= $this->www('css/module/master.css') ?>" type="text/css" media="screen"/>
<script type="text/javascript" src="<?= $this->www('script/module/master.log.js') ?>"></script>

<? $this->view('body') ?>
<? $this->view('master/header', array('tab' => 'zdgl')) ?>

<div class="ftt-container">
    <div class="ftt-title">
        <h2 class="column-left">账单日志</h2>
        <input type="button" value="返回" class="button white column-right" onclick="history.go(-1)" />
    </div>
    <div class="search">
        <form id="form-log-bill-index" method="get" action="/master/log/bill">
            <input type="hidden" name="bid" value="<?= $this->bill['b_id'] ?>" />
            <span>查找范围：</span>
            <input type="text" name="bdate" value="<?= $this->query['bdate'] ?>" class="ftt-input-text short-text input-datepicker dateISO" />
            -
            <input type="text" name="edate" value="<?= $this->query['edate'] ?>" class="ftt-input-text short-text input-datepicker dateISO" />
            <span>每页显示：</span>
            <input type="text" name="qnty" value="<?= $this->query['qnty'] ?>" class="ftt-input-text single-text {integer:true, range:[1, 30]}" />
            <span>条</span>
            <input type="submit" value="提交" class="button white" />
        </form>
    </div>
    <table class="data">
        <thead>
            <tr>
                <th>编号</th>
                <th>账单名</th>
                <th>事项</th>
                <th>操作人员</th>
                <th>操作时间</th>
                <th>操作IP</th>
            </tr>
        </thead>
        <tbody>
            <? if (empty($this->logs)): ?>
            <tr>
                <td colspan="6">没有任何记录</td>
            </tr>
            <? else: ?>
            <? foreach ($this->logs as $log): ?>
            <tr>
                <td><?= $log['lb_id'] ?></td>
                <td><?= $this->escape($log['lb_xnm']) ?></td>
                <td>
                    <?= $this->escape($log['lb_name'] . ($log['lb_memo'] == '' ? '' : '(' . $log['lb_memo'] . ')')) ?>
                </td>
                <td><?= $this->escape($log['lb_pnm']) ?></td>
                <td><?= $this->escape($log['lb_date']) ?></td>
                <td><?= $this->escape($log['lb_ip']) ?></td>
            </tr>
            <? endforeach; ?>
            <? endif; ?>
        </tbody>
    </table>
    <? $this->view('master/pager', array('pager' => $this->pager)) ?>
</div>

<? $this->view('master/footer') ?>
<script type="text/javascript">
$(Z.Module.master.log.bill.init);
</script>
<? $this->view('foot') ?>
