<? $this->view('head') ?>
<title>密码重设</title>
<link rel="stylesheet" href="<?= $this->www('css/module/index.css') ?>" type="text/css" media="screen"/>
<script type="text/javascript" src="<?= $this->www('script/module/master.index.js') ?>"></script>

<? $this->view('body') ?>
<? $this->view('default/header') ?>
        <div class="content-wrapper">
            <div class="form_block form_block-simple">
                <fieldset>
                    <legend><?= $this->escape($this->user['u_realname']) ?> (<?= $this->escape($this->user['u_email']) ?>)</legend>
                    <p>请输入新密码，完成重设密码操作。</p>
                    <form action="<?= $this->forward ?>" method="post" id="form-reset-password-recovery">
                        <p><label for="form-reset-password">新密码</label><input type="password" name="password" id="form-reset-password" class="text required" /></p>
                        <p><label for="form-reset-password-repeated">确认密码</label><input type="password" name="password-repeated" id="form-reset-password-repeated" class="text {required:true,minlength:6,equalTo:'#form-reset-password-password'}" /></p>
                        <p><input type="submit" value="重设密码" class="button green" /></p>
                    </form>
                </fieldset>
            </div>
        </div>
<? $this->view('default/footer') ?>
<script type="text/javascript">$(Z.Module.master.index.resetPassword.init)</script>
<? $this->view('foot') ?>
