    <div id="header">
        <div class="wrapper clearfix">
            <h1 class="header-ftt_logo"><a href="/"><img src="<?= $this->www('img/ftt_logo.png') ?>" alt="房态通"></a></h1>
            <ul class="header-login">
                <li><a href="/master/index/signin">登录</a></li>
                <li><a href="/master/index/signup">注册</a></li>
            </ul>
            <!-- <p class="header-hot_line">7 × 24小时客服电话热线：400-xxxx-xxxx</p> -->
        </div>
    </div>
    <div id="container">
